## Importing

In [1]:
import pandas as pd

## Loading and Retrieving data

In [52]:
df=pd.read_csv("foodmenu.tsv",sep='\t')
df.head(7)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
6,3,1,Side of Chips,NaN,1.69

In [53]:
df.tail()

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [54]:
df.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

In [6]:
df.shape

(4622, 5)

In [7]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

## Selecting Data

In [8]:
df['item_name']

0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
5                                Chicken Bowl
6                               Side of Chips
7                               Steak Burrito
8                            Steak Soft Tacos
9                               Steak Burrito
10                        Chips and Guacamole
11                       Chicken Crispy Tacos
12                         Chicken Soft Tacos
13                               Chicken Bowl
14                        Chips and Guacamole
15      Chips and Tomatillo-Green Chili Salsa
16                            Chicken Burrito
17                            Chicken Burrito
18                                Canned Soda
19                               Chicken Bowl
20                        Chips and Guacamole
21                           Barbacoa Burrito
22                           Nantucket Nectar
23                            Chicken Burrito
24                                       Izze
25               Chips and Fresh Tomato Salsa
26                               Chicken Bowl
27                           Carnitas Burrito
28                                Canned Soda
29                            Chicken Burrito
                        ...
4592                         Barbacoa Burrito
4593                            Carnitas Bowl
4594                            Barbacoa Bowl
4595                             Chicken Bowl
4596                      Chips and Guacamole
4597                        Canned Soft Drink
4598                            Bottled Water
4599                             Chicken Bowl
4600                      Chips and Guacamole
4601                        Canned Soft Drink
4602                         Barbacoa Burrito
4603                         Barbacoa Burrito
4604                             Chicken Bowl
4605                      Chips and Guacamole
4606                        Canned Soft Drink
4607                            Steak Burrito
4608                           Veggie Burrito
4609                        Canned Soft Drink
4610                            Steak Burrito
4611                           Veggie Burrito
4612                            Carnitas Bowl
4613                                    Chips
4614                            Bottled Water
4615                       Chicken Soft Tacos
4616                      Chips and Guacamole
4617                            Steak Burrito
4618                            Steak Burrito
4619                       Chicken Salad Bowl
4620                       Chicken Salad Bowl
4621                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: object

In [68]:
df[['item_name','item_price']]

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
9                             Steak Burrito        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
13                             Chicken Bowl       11.25
14                      Chips and Guacamole        4.45
15    Chips and Tomatillo-Green Chili Salsa        2.39
16                          Chicken Burrito        8.49
17                          Chicken Burrito        8.49
18                              Canned Soda        2.18
19                             Chicken Bowl        8.75
20                      Chips and Guacamole        4.45
21                         Barbacoa Burrito        8.99
22                         Nantucket Nectar        3.39
23                          Chicken Burrito       10.98
24                                     Izze        3.39
25             Chips and Fresh Tomato Salsa        2.39
26                             Chicken Bowl        8.49
27                         Carnitas Burrito        8.99
28                              Canned Soda        1.09
29                          Chicken Burrito        8.49
...                                     ...         ...
4592                       Barbacoa Burrito       11.75
4593                          Carnitas Bowl       11.75
4594                          Barbacoa Bowl       11.75
4595                           Chicken Bowl        8.75
4596                    Chips and Guacamole        4.45
4597                      Canned Soft Drink        1.25
4598                          Bottled Water        1.50
4599                           Chicken Bowl        8.75
4600                    Chips and Guacamole        4.45
4601                      Canned Soft Drink        1.25
4602                       Barbacoa Burrito        9.25
4603                       Barbacoa Burrito        9.25
4604                           Chicken Bowl        8.75
4605                    Chips and Guacamole        4.45
4606                      Canned Soft Drink        1.25
4607                          Steak Burrito       11.75
4608                         Veggie Burrito       11.25
4609                      Canned Soft Drink        1.25
4610                          Steak Burrito       11.75
4611                         Veggie Burrito       11.25
4612                          Carnitas Bowl        9.25
4613                                  Chips        2.15
4614                          Bottled Water        1.50
4615                     Chicken Soft Tacos        8.75
4616                    Chips and Guacamole        4.45
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

In [33]:
#Returns data by position (numerical index)
df.iloc[0]

order_id                                         1
quantity                                         1
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                  $2.39
Name: 0, dtype: object

In [55]:
#Returns data of first 3 rows
df.iloc[0:3,:]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39

In [17]:
#Returns third element of first row 
df.iloc[0,2]

'Chips and Fresh Tomato Salsa'

In [56]:
#Return data by labelled index
df.loc[[0,3,5]]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98

## Filtering Data

In [57]:
df[df['quantity'] > 4]

,order_id,quantity,item_name,choice_description,item_price
2441,970,5,Bottled Water,NaN,7.50
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25
3599,1443,7,Bottled Water,NaN,10.50
3887,1559,8,Side of Chips,NaN,13.52
4152,1660,10,Bottled Water,NaN,15.00

In [58]:
df[(df['quantity'] > 4) & (df['item_name']== 'Side of Chips')]

      order_id  quantity      item_name choice_description  item_price
3887      1559         8  Side of Chips                NaN       13.52

## Sorting Data

In [59]:
df.sort_values('quantity',ascending= False)

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25
4152,1660,10,Bottled Water,NaN,15.00
3887,1559,8,Side of Chips,NaN,13.52
3599,1443,7,Bottled Water,NaN,10.50
2441,970,5,Bottled Water,NaN,7.50
4491,1786,4,Canned Soft Drink,[Sprite],5.00
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00
1425,577,4,Bottled Water,NaN,6.00
4489,1786,4,Chips and Guacamole,NaN,17.80
4490,1786,4,Canned Soft Drink,[Coke],5.00
2235,901,4,Canned Soda,[Sprite],4.36
1880,759,4,Bottled Water,NaN,6.00
1257,511,4,Chips and Fresh Tomato Salsa,NaN,11.80
3973,1592,4,Canned Soft Drink,[Coke],5.00
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",32.94
917,379,3,Canned Soft Drink,[Lemonade],3.75
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75
3603,1443,3,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",27.75
3089,1231,3,Canned Soft Drink,[Diet Coke],3.75
2823,1121,3,Bottled Water,NaN,3.27
850,350,3,Canned Soft Drink,[Sprite],3.75
3270,1309,3,Chips and Tomatillo-Red Chili Salsa,NaN,7.17
4186,1671,3,Bottled Water,NaN,4.50
3634,1454,3,Chicken Burrito,[Fresh Tomato Salsa],26.25
4137,1655,3,Bottled Water,NaN,4.50
3636,1454,3,Chicken Burrito,"[Fresh Tomato Salsa, Rice]",26.25
4098,1642,3,Canned Soft Drink,[Diet Coke],3.75
818,338,3,Bottled Water,NaN,3.27
3128,1247,3,Canned Soft Drink,[Diet Coke],3.75
...,...,...,...,...,...
1575,638,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Fajita Veget...",8.75
1574,637,1,Canned Soft Drink,[Diet Coke],1.25
1573,637,1,Chips and Tomatillo Green Chili Salsa,NaN,2.95
1572,637,1,Chips and Guacamole,NaN,4.45
1570,637,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
1596,647,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.25
1569,636,1,Chicken Burrito,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",8.75
1568,636,1,Chips and Tomatillo Green Chili Salsa,NaN,2.95
1567,636,1,Chicken Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, L...",8.75
1565,635,1,Chicken Burrito,"[Fresh Tomato Salsa, Rice]",8.75
1564,635,1,Chips and Guacamole,NaN,4.45
1563,635,1,Steak Bowl,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
1578,638,1,Canned Soft Drink,[Sprite],1.25
1579,639,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice]]",8.75
1580,639,1,Chips,NaN,2.15
1581,639,1,Canned Soft Drink,[Diet Coke],1.25
1582,640,1,Steak Burrito,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
1583,640,1,Chips and Tomatillo Green Chili Salsa,NaN,2.95
1584,641,1,Barbacoa Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Rice, ...",8.99
1585,641,1,Nantucket Nectar,[Peach Orange],3.39
1586,642,1,Steak Burrito,"[Roasted Chili Corn Salsa, [Black Beans, Chees...",9.25
1587,642,1,Carnitas Soft Tacos,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",9.25
1589,643,1,Chips and Tomatillo Green Chili Salsa,NaN,2.95
1590,644,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.89
1591,644,1,Bottled Water,NaN,1.50
1592,645,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1593,645,1,Chips and Tomatillo Green Chili Salsa,NaN,2.95
1594,646,1,Carnitas Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",9.25
1595,646,1,Chicken Burrito,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.25
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [62]:
#Sorting first by quantity in ascending order then item_price in descending order
df.sort_values(['quantity','item_price'],ascending= [True, False])

,order_id,quantity,item_name,choice_description,item_price
606,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Cheese, Gua...",11.89
749,309,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Cheese, Lett...",11.89
1132,468,1,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.89
1159,478,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.89
1229,501,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.89
1311,534,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
1326,541,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.89
1505,612,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",11.89
1571,637,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",11.89
1590,644,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.89
1816,734,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.89
2401,953,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Guaca...",11.89
2439,969,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.89
2442,970,1,Barbacoa Salad Bowl,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.89
2610,1035,1,Carnitas Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
2740,1088,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.89
2804,1114,1,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",11.89
2957,1176,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",11.89
3120,1244,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
3208,1283,1,Barbacoa Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",11.89
3350,1343,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Cheese, Guacamole, Lettu...",11.89
3493,1403,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
3546,1426,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, Guacamole]",11.89
3749,1499,1,Carnitas Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
4239,1692,1,Carnitas Salad Bowl,"[Tomatillo Green Chili Salsa, [Black Beans, Ch...",11.89
4313,1720,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
43,20,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",11.75
58,27,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
...,...,...,...,...,...
2936,1167,3,Chips,NaN,6.45
2944,1170,3,Side of Chips,NaN,5.07
3294,1321,3,Bottled Water,NaN,4.50
3314,1328,3,Bottled Water,NaN,4.50
4137,1655,3,Bottled Water,NaN,4.50
4186,1671,3,Bottled Water,NaN,4.50
689,284,3,Canned Soft Drink,[Diet Coke],3.75
850,350,3,Canned Soft Drink,[Sprite],3.75
917,379,3,Canned Soft Drink,[Lemonade],3.75
1559,633,3,Canned Soft Drink,[Coke],3.75
3089,1231,3,Canned Soft Drink,[Diet Coke],3.75
3128,1247,3,Canned Soft Drink,[Diet Coke],3.75
4098,1642,3,Canned Soft Drink,[Diet Coke],3.75
818,338,3,Bottled Water,NaN,3.27
2823,1121,3,Bottled Water,NaN,3.27
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00
4489,1786,4,Chips and Guacamole,NaN,17.80
1257,511,4,Chips and Fresh Tomato Salsa,NaN,11.80
1425,577,4,Bottled Water,NaN,6.00
1880,759,4,Bottled Water,NaN,6.00
3973,1592,4,Canned Soft Drink,[Coke],5.00
4490,1786,4,Canned Soft Drink,[Coke],5.00
4491,1786,4,Canned Soft Drink,[Sprite],5.00
2235,901,4,Canned Soda,[Sprite],4.36
2441,970,5,Bottled Water,NaN,7.50
3599,1443,7,Bottled Water,NaN,10.50
3887,1559,8,Side of Chips,NaN,13.52
4152,1660,10,Bottled Water,NaN,15.00
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

## Grouping data

In [40]:
#To find most ordered item in choice_description column
mst_ord=df.groupby('choice_description').sum()
mst_ord.sort_values('quantity',ascending= False).head(1)

                    order_id  quantity
choice_description
[Diet Coke]           123455       159

## Dealing with missing values

In [63]:
#Return True for null and false for non-null values
pd.isnull(df)

      order_id  quantity  item_name  choice_description  item_price
0        False     False      False                True       False
1        False     False      False               False       False
2        False     False      False               False       False
3        False     False      False                True       False
4        False     False      False               False       False
5        False     False      False               False       False
6        False     False      False                True       False
7        False     False      False               False       False
8        False     False      False               False       False
9        False     False      False               False       False
10       False     False      False                True       False
11       False     False      False               False       False
12       False     False      False               False       False
13       False     False      False               False       False
14       False     False      False                True       False
15       False     False      False                True       False
16       False     False      False               False       False
17       False     False      False               False       False
18       False     False      False               False       False
19       False     False      False               False       False
20       False     False      False                True       False
21       False     False      False               False       False
22       False     False      False               False       False
23       False     False      False               False       False
24       False     False      False               False       False
25       False     False      False                True       False
26       False     False      False               False       False
27       False     False      False               False       False
28       False     False      False               False       False
29       False     False      False               False       False
...        ...       ...        ...                 ...         ...
4592     False     False      False               False       False
4593     False     False      False               False       False
4594     False     False      False               False       False
4595     False     False      False               False       False
4596     False     False      False                True       False
4597     False     False      False               False       False
4598     False     False      False                True       False
4599     False     False      False               False       False
4600     False     False      False                True       False
4601     False     False      False               False       False
4602     False     False      False               False       False
4603     False     False      False               False       False
4604     False     False      False               False       False
4605     False     False      False                True       False
4606     False     False      False               False       False
4607     False     False      False               False       False
4608     False     False      False               False       False
4609     False     False      False               False       False
4610     False     False      False               False       False
4611     False     False      False               False       False
4612     False     False      False               False       False
4613     False     False      False                True       False
4614     False     False      False                True       False
4615     False     False      False               False       False
4616     False     False      False                True       False
4617     False     False      False               False       False
4618     False     False      False               False       False
4619     False     False      False               False       False
4620     False     False      False               False       False
4621     False     False      False               False       False

[4622 rows x 5 columns]

In [64]:
pd.isnull(df).sum() 
# or 
# df.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [65]:
df.dropna(axis=1)

      order_id  quantity                              item_name  item_price
0            1         1           Chips and Fresh Tomato Salsa        2.39
1            1         1                                   Izze        3.39
2            1         1                       Nantucket Nectar        3.39
3            1         1  Chips and Tomatillo-Green Chili Salsa        2.39
4            2         2                           Chicken Bowl       16.98
5            3         1                           Chicken Bowl       10.98
6            3         1                          Side of Chips        1.69
7            4         1                          Steak Burrito       11.75
8            4         1                       Steak Soft Tacos        9.25
9            5         1                          Steak Burrito        9.25
10           5         1                    Chips and Guacamole        4.45
11           6         1                   Chicken Crispy Tacos        8.75
12           6         1                     Chicken Soft Tacos        8.75
13           7         1                           Chicken Bowl       11.25
14           7         1                    Chips and Guacamole        4.45
15           8         1  Chips and Tomatillo-Green Chili Salsa        2.39
16           8         1                        Chicken Burrito        8.49
17           9         1                        Chicken Burrito        8.49
18           9         2                            Canned Soda        2.18
19          10         1                           Chicken Bowl        8.75
20          10         1                    Chips and Guacamole        4.45
21          11         1                       Barbacoa Burrito        8.99
22          11         1                       Nantucket Nectar        3.39
23          12         1                        Chicken Burrito       10.98
24          12         1                                   Izze        3.39
25          13         1           Chips and Fresh Tomato Salsa        2.39
26          13         1                           Chicken Bowl        8.49
27          14         1                       Carnitas Burrito        8.99
28          14         1                            Canned Soda        1.09
29          15         1                        Chicken Burrito        8.49
...        ...       ...                                    ...         ...
4592      1825         1                       Barbacoa Burrito       11.75
4593      1825         1                          Carnitas Bowl       11.75
4594      1825         1                          Barbacoa Bowl       11.75
4595      1826         1                           Chicken Bowl        8.75
4596      1826         1                    Chips and Guacamole        4.45
4597      1826         1                      Canned Soft Drink        1.25
4598      1826         1                          Bottled Water        1.50
4599      1827         1                           Chicken Bowl        8.75
4600      1827         1                    Chips and Guacamole        4.45
4601      1827         1                      Canned Soft Drink        1.25
4602      1827         1                       Barbacoa Burrito        9.25
4603      1827         1                       Barbacoa Burrito        9.25
4604      1828         1                           Chicken Bowl        8.75
4605      1828         1                    Chips and Guacamole        4.45
4606      1828         1                      Canned Soft Drink        1.25
4607      1829         1                          Steak Burrito       11.75
4608      1829         1                         Veggie Burrito       11.25
4609      1829         1                      Canned Soft Drink        1.25
4610      1830         1                          Steak Burrito       11.75
4611      1830         1                         Veggie Burrito       11.25
4612      1831         1                          Carnitas Bowl        9.25
4613      1831         1                                  Chips        2.15
4614      1831         1                          Bottled Water        1.50
4615      1832         1                     Chicken Soft Tacos        8.75
4616      1832         1                    Chips and Guacamole        4.45
4617      1833         1                          Steak Burrito       11.75
4618      1833         1                          Steak Burrito       11.75
4619      1834         1                     Chicken Salad Bowl       11.25
4620      1834         1                     Chicken Salad Bowl        8.75
4621      1834         1                     Chicken Salad Bowl        8.75

[4622 rows x 4 columns]

In [66]:
df.dropna()

,order_id,quantity,item_name,choice_description,item_price
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49
18,9,2,Canned Soda,[Sprite],2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
24,12,1,Izze,[Grapefruit],3.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.99
28,14,1,Canned Soda,[Dr. Pepper],1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49
31,16,1,Steak Burrito,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",8.99
33,17,1,Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",8.99
35,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, Rice]",8.75
36,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
43,20,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",11.75
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75
...,...,...,...,...,...
4583,1823,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75
4585,1823,1,Canned Soft Drink,[Diet Coke],1.25
4586,1824,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
4587,1824,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.25
4589,1825,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.25
4590,1825,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",8.75
4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",11.75
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75
4597,1826,1,Canned Soft Drink,[Nestea],1.25
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75
4601,1827,1,Canned Soft Drink,[Diet Coke],1.25
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
4606,1828,1,Canned Soft Drink,[Coke],1.25
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4609,1829,1,Canned Soft Drink,[Sprite],1.25
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",8.75
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [67]:
df.fillna(0)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,0,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,0,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
6,3,1,Side of Chips,0,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25
10,5,1,Chips and Guacamole,0,4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
14,7,1,Chips and Guacamole,0,4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,0,2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49
18,9,2,Canned Soda,[Sprite],2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75
20,10,1,Chips and Guacamole,0,4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
24,12,1,Izze,[Grapefruit],3.39
25,13,1,Chips and Fresh Tomato Salsa,0,2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.99
28,14,1,Canned Soda,[Dr. Pepper],1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49
...,...,...,...,...,...
4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",11.75
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75
4596,1826,1,Chips and Guacamole,0,4.45
4597,1826,1,Canned Soft Drink,[Nestea],1.25
4598,1826,1,Bottled Water,0,1.50
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75
4600,1827,1,Chips and Guacamole,0,4.45
4601,1827,1,Canned Soft Drink,[Diet Coke],1.25
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
4605,1828,1,Chips and Guacamole,0,4.45
4606,1828,1,Canned Soft Drink,[Coke],1.25
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4609,1829,1,Canned Soft Drink,[Sprite],1.25
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25
4613,1831,1,Chips,0,2.15
4614,1831,1,Bottled Water,0,1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",8.75
4616,1832,1,Chips and Guacamole,0,4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75